[package]
name = "gchemol"
version = "0.0.37"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]
description = "gchemol: a Graph-based CHEMical Objects Library"
homepage = "https://github.com/gchemol/gchemol"
repository = "https://github.com/gchemol/gchemol"
license = "MIT OR Apache-2.0"

[dependencies]
gchemol-core = "0.0.37"
gchemol-readwrite = "0.0.36"
gchemol-geometry = "0.0.36"
# gchemol-core = {path = "../gchemol-core"}
# gchemol-readwrite = {path = "../gchemol-readwrite"}
# gchemol-geometry = {path = "../gchemol-geometry"}

[dev-dependencies]
tempfile = "3"
approx = "0.3"
